config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'places#index'
  namespace :places do
    resources :searches, only: [:index, :new, :create, :show]
  end
  resources :places, only: [:index, :show, :new] do
  collection do
    get 'searchword'
  end
  collection do
    get 'searchresult'
  end
end
  resources :posts
  resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :search

  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, only: :show

  def show
    @user = User.find(params[:id])
    @searches = @user.search
  end

  private
  def move_to_index
    redirect_to root_path unless user_signed_in? && current_user.id == params[:id].to_i
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if current_user.try(:admin?) %>
      <div class="page-header">
        <h1>管理者マイページ</h1>
        <%= link_to "ユーザー情報を編集する", edit_user_registration_path, class: "mypage_user_edit" %>
      </div>
      <p class="admin_btn col-xs-offset-1 col-xs-10 col-xs-offset-1"><%= link_to "管理画面", "/admin" %></p>
  <% else %>
    <div class="page-header">
      <div class="mypage_head">マイページ</div>
      <%= link_to "ユーザー情報を編集する", edit_user_registration_path, class: "mypage_user_edit" %>
    </div>
<% end %>



<% @posts.each do |post| %>
  <div class="content">
    <div class="content__left">
      <div class="content__left--image"></div>
    </div>
    <div class="content__right">
      <div class="content__right__top">
        場所: <%= post.place %>
      </div>
      <div class="content__right__top">
        オススメ文: <%= post.content %>
      </div>
      <div class="content__right__bottom">
        <div class="content__right__bottom--date">
          <%= post.created_at %>
        </div>
        <%= link_to "詳細", post_path(post.id), class: "content__right__top--title" %>
      </div>
    </div>
  </div>
<% end %>