config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'places#index'
  namespace :places do
    resources :searches, only: [:index, :new, :create, :show]
  end
  resources :places, only: [:index, :show, :new] do
  collection do
    get 'searchword'
  end
  collection do
    get 'searchresult'
  end
end
  resources :posts
  resources :users, only: :show
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :subplace, optional: true
  has_many :search

  def self.search(search)
    return Place.all unless search
    Place.where('name LIKE(?)', "%#{search}%")
  end

  def self.gurunaviApi(place, food)
        # 住所の正規表現  メインの場所の住所を使う
    place_address = place.address

    rex = /(...??[都道府県])((?:旭川|伊達|石狩|盛岡|奥州|田村|南相馬|那須塩原|東村山|武蔵村山|羽村|十日町|上越|富山|野々市|大町|蒲郡|四日市|姫路|大和郡山|廿日市|下松|岩国|田川|大村)市|.+?郡(?:玉村|大町|.+?)[町村]|.+?市.+?区|.+?[市区町村])(.+)/
    rex_address = place_address.match(rex).captures
    rex_address1 = rex_address[0]
    rex_address2 = rex_address[1]
    
      # hash形式でパラメタ文字列を指定し、URL形式にエンコード

    paramskey = URI.encode_www_form({freeword: "#{rex_address1},#{rex_address2},#{food}"})

    gurunavi_keyid = ENV["GURUNAVI_PRIVATE_KEY"]

    uri = URI.parse("https://api.gnavi.co.jp/RestSearchAPI/v3/?keyid=#{gurunavi_keyid}&#{paramskey}")

    result = allApi(uri)
    if result == "404 NOT FOUND" && food.include?("ランチ")
    paramskey = URI.encode_www_form({freeword: "#{rex_address1},#{rex_address2},ランチ"})
    uri = URI.parse("https://api.gnavi.co.jp/RestSearchAPI/v3/?keyid=#{gurunavi_keyid}&#{paramskey}")
    result = allApi(uri)
    elsif result == "404 NOT FOUND"
    paramskey = URI.encode_www_form({freeword: "#{rex_address1},#{rex_address2}"})
    uri = URI.parse("https://api.gnavi.co.jp/RestSearchAPI/v3/?keyid=#{gurunavi_keyid}&#{paramskey}")
    result = allApi(uri)
    else
    end
    sample1 = result["@attributes"]
    sample2 = result["rest"][0]
    name = result["rest"][0]["name"]
    text = result["rest"][0]["pr"]["pr_short"]
    link = result["rest"][0]["url"]
    image = result["rest"][0]["image_url"]["shop_image1"]
    address = result["rest"][0]["address"]
    tel = result["rest"][0]["tel"]
    lunch = result["rest"][0]["lunch"]
    category = result["rest"][0]["code"]["category_name_s"][0]
    holiday = result["rest"][0]["holiday"]
    budget = result["rest"][0]["budget"]
    areaname_s = result["rest"][0]["code"]["areaname_s"]
    gurunaviapiHash1 = {name: name, text: text, image: image, address: address, link: link}
    return gurunaviapiHash1

    
  end


  def self.googleApi_waypoint(**waypoint_hash)

    origin = waypoint_hash[:origin]
    waypoint1 = waypoint_hash[:waypoint1]
    waypoint2 = waypoint_hash[:waypoint2]
    destination = waypoint_hash[:destination]
    # subplaceがない場合中身はnil
    waypoint3 = waypoint_hash[:waypoint3]


        # hash形式でパラメタ文字列を指定し、URL形式にエンコード
        origin_params = URI.encode_www_form({origin: "#{origin}"})
        waypoint1_params = URI.encode_www_form({destination: "#{waypoint1}"})
        waypoint2_params = URI.encode_www_form({destination: "#{waypoint2}"})
        destination_params = URI.encode_www_form({destination: "#{destination}"})
        google_keyid = ENV["GOOGLE_DIRECTIONS_PRIVATE_KEY"]
       
        if waypoint3
          waypoint3_params = URI.encode_www_form({destination: "#{waypoint3}"})
          uri2 = URI.parse("https://maps.googleapis.com/maps/api/directions/json?origin=#{origin_params}&destination=#{destination_params}&waypoints=#{waypoint1_params}|#{waypoint2_params}|#{waypoint3_params}&key=#{google_keyid}")
        else
          uri2 = URI.parse("https://maps.googleapis.com/maps/api/directions/json?origin=#{origin_params}&destination=#{destination_params}&waypoints=#{waypoint1_params}|#{waypoint2_params}&key=#{google_keyid}")
        end

        map_result = Place.allApi(uri2)

        # map_duration = map_result["routes"][0]["legs"][0]["duration"]["value"]
        # mapapihash1 = {map_duration: map_duration}
       return map_result
  end


  
  private
  def self.allApi(uri)
       # https  sslを使用する場合
       http = Net::HTTP.new(uri.host, uri.port)
       http.use_ssl = uri.scheme === "https"
       http.open_timeout = 5
       http.read_timeout = 10
       http.start
       response = http.get(uri.request_uri)
       http.finish
     # 例外処理の開始
    begin
       # responseの値に応じて処理を分ける
       case response
       # 成功した場合
       when Net::HTTPSuccess
         # responseのbody要素をJSON形式で解釈し、hashに変換
         result1 = JSON.parse(response.body)
       # 別のURLに飛ばされた場合
       when Net::HTTPRedirection
         message = "Redirection: code=#{response.code} message=#{response.message}"
              # 404エラー時
       when Net::HTTPNotFound
         message = "404 NOT FOUND"
       # その他エラー
       else
         message = "HTTP ERROR: code=#{response.code} message=#{response.message}"
       end
     # エラー時処理
     rescue IOError => e
       message = "e.message"
     rescue TimeoutError => e
       message = "e.message"
     rescue JSON::ParserError => e
       message = "e.message"
     rescue => e
       message = "e.message"
     
   end

  end

end

app/controllers/places/searches_controller.rb
class Places::SearchesController < ApplicationController

  def index
    @searches = Search.includes(:user).order("created_at DESC")
  end

  def new
    @search = Search.new

    # 時間
    @place = Place.find(params[:placeid])
    @subplace = Subplace.find_by(place_id: params[:placeid])
    @date = params[:example1]

  # ぐるなびAPIでレストラン検索 ディナー
    @food = params[:food]
    gurunaviapiHash = Place.gurunaviApi(@place, @food)
    @restaurant_name = gurunaviapiHash[:name]
    @restaurant_text = gurunaviapiHash[:text]
    @restaurant_image = gurunaviapiHash[:image]
    @restaurant_address = gurunaviapiHash[:address]
    @restaurant_link = gurunaviapiHash[:link]

  # ぐるなびAPIでレストラン検索 ランチ
    @lunch = params[:lunch]
    lunch_gurunaviapiHash = Place.gurunaviApi(@place, @lunch)
    @lunch_restaurant_name = lunch_gurunaviapiHash[:name]
    @lunch_restaurant_text = lunch_gurunaviapiHash[:text]
    @lunch_restaurant_image = lunch_gurunaviapiHash[:image]
    @lunch_restaurant_address = lunch_gurunaviapiHash[:address]
    @lunch_restaurant_link = lunch_gurunaviapiHash[:link]

  # googleDerectionAPIで移動時間検索
    departure = params[:departure]
    place_address = @place.address

  # # 出発地とメインの行き先の２点間の経過時間検索
  #  mapapiHash = Place.googleApi(departure, place_address)
  #  @map_duration = mapapiHash[:map_duration]

    if @subplace
      # 出発地、ランチ場所、メインの行き先、サブの行き先、ディナーの場所の５点間の経過時間
      subplace_address = @subplace.address
      # mapapiHash3 = Place.googleApi_waypoint2(departure, @lunch_restaurant_address, place_address, subplace_address, @restaurant_address)
      mapapiHash3 = Place.googleApi_waypoint(origin: departure, waypoint1: @lunch_restaurant_address, waypoint2: place_address,waypoint3: subplace_address ,destination: @restaurant_address)
      @section1 = mapapiHash3["routes"][0]["legs"][0]["duration"]["value"]
      @section2 = mapapiHash3["routes"][0]["legs"][1]["duration"]["value"]
      @section3 = mapapiHash3["routes"][0]["legs"][2]["duration"]["value"]
      @section4 = mapapiHash3["routes"][0]["legs"][3]["duration"]["value"]
    else
      # 出発地、ランチ場所、メインの行き先、ディナーの場所の４点間の経過時間
      mapapiHash2 = Place.googleApi_waypoint(origin: departure, waypoint1: @lunch_restaurant_address, waypoint2: place_address, destination: @restaurant_address)
      @section1 = mapapiHash2["routes"][0]["legs"][0]["duration"]["value"]
      @section2 = mapapiHash2["routes"][0]["legs"][1]["duration"]["value"]
      @section3 = mapapiHash2["routes"][0]["legs"][2]["duration"]["value"]
    end
  end

  def create
    Search.create(search_params)
    redirect_to places_searches_path
  end

  def show
    @if_true = params[:if_true]

    @search_date = params[:search_date]
    @search = Search.find(params[:id])
    @place = Place.find(@search.place_id)
    if @search.subplace_id
    @subplace = Subplace.find(@search.subplace_id)
    end
    @date = @search.went_date
    @restaurant_name = @search.dinner_name
    @restaurant_text = @search.dinner_text
    @restaurant_image = @search.dinner_image
    @restaurant_address = @search.dinner_address
    @restaurant_link = @search.dinner_link
    @lunch_restaurant_name = @search.lunch_name
    @lunch_restaurant_text = @search.lunch_text
    @lunch_restaurant_image = @search.lunch_image
    @lunch_restaurant_address = @search.lunch_address
    @lunch_restaurant_link = @search.lunch_link

    departure = params[:departure]
    place_address = @place.address

  if @if_true && @subplace
    # 出発地、ランチ場所、メインの行き先、サブの行き先、ディナーの場所の５点間の経過時間
    subplace_address = @subplace.address
    # mapapiHash3 = Place.googleApi_waypoint2(departure, @lunch_restaurant_address, place_address, subplace_address, @restaurant_address)
    mapapiHash3 = Place.googleApi_waypoint(origin: departure, waypoint1: @lunch_restaurant_address, waypoint2: place_address,waypoint3: subplace_address ,destination: @restaurant_address)
    @section1 = mapapiHash3["routes"][0]["legs"][0]["duration"]["value"]
    @section2 = mapapiHash3["routes"][0]["legs"][1]["duration"]["value"]
    @section3 = mapapiHash3["routes"][0]["legs"][2]["duration"]["value"]
    @section4 = mapapiHash3["routes"][0]["legs"][3]["duration"]["value"]
  elsif @if_true && !@subplace
    # 出発地、ランチ場所、メインの行き先、ディナーの場所の４点間の経過時間
    mapapiHash2 = Place.googleApi_waypoint(origin: departure, waypoint1: @lunch_restaurant_address, waypoint2: place_address, destination: @restaurant_address)
    @section1 = mapapiHash2["routes"][0]["legs"][0]["duration"]["value"]
    @section2 = mapapiHash2["routes"][0]["legs"][1]["duration"]["value"]
    @section3 = mapapiHash2["routes"][0]["legs"][2]["duration"]["value"]
  else
    @section1 = @search.section1
    @section2 = @search.section2
    @section3 = @search.section3
    @section4 = @search.section4
  end


  end

  private
  def search_params
    params.required(:search).permit(:lunch_name, :lunch_text, :lunch_image, :lunch_address, :lunch_link, :dinner_name, :dinner_text, :dinner_image, :dinner_address, :dinner_link, :section1, :section2, :section3, :section4, :plan_comment, :went_date, :place_id, :subplace_id, :user_id)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def show
  end

  def searchword
    @places = Place.search(params[:keyword])
  end

  def searchresult
    @place = Place.find(params[:key])
    @places = Place.all
  end

end

# {"date1"=>"", "time1"=>"", "time2"=>"", "controller"=>"places", "action"=>"search"}
# {"date1"=>"2020-01-18", "time1"=>"12:30", "time2"=>"21:00", "RadioGroup1"=>"20", "controller"=>"places", "action"=>"search"} permitted: false>

app/helpers/places/searches_helper.rb
module Places::SearchesHelper

  # ランチの時間の設定
  @@set_lunch_time = "11:30"
  @@set_lunch_end = "12:30"
  @@stay_time_a = 6
  @@stay_time_b = 4
  @@subplace_stay_time = 2

  def strDate(dateTime)
    date = Date.parse("#{dateTime}")
   "#{date}"
  end

  #string型のオブジェクトをパースしTimeオブジェクトに変換し、00:00の形にし、string型に戻して出力
  def strTime(time1)
    timex1 = Time.parse("#{time1}")
    strTimex1 = timex1.strftime("%H:%M")
    "#{strTimex1}"
  end

  def display_lunch_time
    "#{@@set_lunch_time} 〜 #{@@set_lunch_end}"
  end

  def display_lunch_arrival
    @@set_lunch_time
  end


  # 出発時間の計算ランチの時間(11:30)から、出発からランチ場所までの経過時間を引く
  def calc_departure_time(date, section1)
    set_lunch_time1 = date + "T" + @@set_lunch_time
    slt = Time.parse("#{set_lunch_time1}")
    section1_per_five = per_five_minutes(section1)
    departure_time = slt - section1_per_five
    departure_time.strftime("%H:%M")
  end

  def place_stay_time(date, section2)
    lunch_end_time = date + "T" + @@set_lunch_end
    let = Time.parse("#{lunch_end_time}")
    section2_per_five = per_five_minutes(section2)
    @arrival_time = let + section2_per_five
    if @subplace
      @plus_stay_time = @arrival_time + @@stay_time_b * 3600
    else
      @plus_stay_time = @arrival_time + @@stay_time_a * 3600
    end
    "#{@arrival_time.strftime("%H:%M")} 〜 #{@plus_stay_time.strftime("%H:%M")}"
  end

  def display_place_arrival
     @arrival_time.strftime("%H:%M")
  end

  def subplace_stay_time(date, section3)
      section3_per_five = per_five_minutes(section3)
      @subplace_arrival = @plus_stay_time + section3_per_five
      @plus_subplace_time = @subplace_arrival + @@subplace_stay_time * 3600
      "#{@subplace_arrival.strftime("%H:%M")} 〜 #{@plus_subplace_time.strftime("%H:%M")}"
  end

  def display_subplace_arrival
      @subplace_arrival.strftime("%H:%M")
  end

  def dinner_start_time(section3or4)
    section3or4_per_five = per_five_minutes(section3or4)
    if @subplace
      @plus_section_time = @plus_subplace_time + section3or4_per_five
    else
      @plus_section_time = @plus_stay_time + section3or4_per_five
    end
    "#{@plus_section_time.strftime("%H:%M")} 〜 "
  end

  def display_dinner_time
    @plus_section_time.strftime("%H:%M")
  end

  private
  def per_five_minutes(duration)
    section_per = duration/300.to_f
    section_per_five = section_per.ceil * 300
  end


end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_choice.html.erb
<nav>
    <ul class="main_menu">
        <li><a href="#"> 都道府県から探す</a>
            <ul>
                <li><a href="">大阪府</a>
                    <ul>
                        <li><a href="#">海遊館</a></li>
                        <li><a href="#">USJ</a></li>
                        <li><a href="#">大阪城</a></li>
                    </ul>
                </li>
                <li><a href="">京都府</a>
                    <ul>
                        <li><a href="#">孫メニュー</a></li>
                        <li><a href="#">孫メニュー</a></li>
                        <li><a href="#">孫メニュー</a></li>
                    </ul>
                </li>
                <li><a href="">兵庫県</a>
                    <ul>
                        <li><a href="#">孫メニュー</a></li>
                        <li><a href="#">孫メニュー</a></li>
                        <li><a href="#">孫メニュー</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><a href="#">種類から探す</a>
            <ul>
                <li><a href="">遊園地</a>
                    <ul>
                    <li><a href="#">USJ</a></li>
                    <li><a href="#">枚方パーク</a></li>
                    <li><a href="#">東京ディズニーランド</a></li>

                    </ul>
                </li>
                <li><a href="">動物園</a>
                    <ul>
                    <li><a href="#">孫メニュー</a></li>
                    <li><a href="#">孫メニュー</a></li>
                    <li><a href="#">孫メニュー</a></li>
                </li>
                    </ul>                        
                </li>
                <li><a href="">公園</a>
                    <ul>
                    <li><a href="#">孫メニュー</a></li>
                    <li><a href="#">孫メニュー</a></li>
                    <li><a href="#">孫メニュー</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</nav>

app/views/places/_footer.html.erb
<div class="copy-group">
  <div class="container-group">
    <p>
      <copy>Copyright© 2020 Transit Inc. All Rights Reserved.</copy><br>
      サイト内の文章、画像等の著作物はTransitに属します。文章・写真などの複製及び無断転載を禁じます。
    </p>
  </div>
</div>

app/views/places/_form.html.erb
<h3>お出かけの条件を入力してください(*は必須)</h3>
<form action="/places/searches/new">

  出発地*<br>
  <input name="departure" type="text" class="address" placeholder="出発地の住所を入力してください" required /> <br>
  お出かけの日時を入力してください*<br>
  <input type="date" name="example1"> <br>
  あなたの性別は？<br>
  <label>
    <input type="radio" name="RadioGroup1" value="20">男性
  </label>
  <label>
    <input type="radio" class="female" class name="RadioGroup1" value="21">女性
  </label><br>
  あなたの年代は？<br>
  <select name="age" >
    <option value="101">10代</option>
    <option value="102">20代</option>
    <option value="103">30代</option>
    <option value="104">40代</option>
    <option value="105">50代</option>
    <option value="106">60代以上</option>
  </select> <br>
  食の好みはありますか？<br>
  <select name="lunch" id="select-food">
    <option value="ランチ">特になし</option>
    <option value="ランチ ラーメン">ラーメン</option>
    <option value="ランチ イタリアン">イタリアン</option>
    <option value="ランチ うどん そば">うどん・そば</option>
    <option value="ランチ カレー">カレー</option>
    <option value="ランチ ファミレス">ファミレス</option>
    <option value="ランチ 洋食">洋食</option>
    <option value="ランチ 寿司">寿司</option>
  </select> ランチ<br>
  <select name="food" id="select-food">
    <option value="ディナー">特になし</option>
    <option value="日本食">日本食</option>
    <option value="イタリアン">イタリアン</option>
    <option value="中華">中華</option>
    <option value="フランス料理">フランス料理</option>
    <option value="ラーメン">ラーメン</option>
    <option value="肉料理">肉料理</option>
  </select> ディナー<br>
  <div>
    <input type="submit" value="条件を送信する" class="submit" id="mainForm">
  </div>
  <input type="hidden" name="placeid" value=<%="#{@place.id}"%>>
</form>

app/views/places/_place.html.erb
<div class="contents2">
  <% @places.each do |place| %>
    <div class="content">
      <div class="content__left">
        <div class="content__left--image"><%= image_tag "#{place.image}", size: '200x200' %></div>
      </div>
      <div class="content__right">
        <div class="content__right__top">
          <%= place.name %>
        </div>
        <div class="content__right__address">
          <%= place.address %>
        </div>
        <div class="content__right__description">
          <%= place.description %>
        </div>
        <div class="content__right__container">
          <div class="content__right__container__link">
            <%= link_to "#{place.link}", "#{place.link}" %>
          </div>
          <div class="content__right__container__go">
            <%= link_to "ここに行く", searchresult_places_path(key: "#{place.id}") %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/places/_searchfunction.html.erb
<form action="/places/searchword" class="search_function">
  <div id="mix">
  <input name="keyword" type='text' id="keyword" class="form-control" placeholder="行きたいメインの場所を検索してください">
  <button type="submit" id="submit" class="btn">検索</button>
  <nav>
    <ul class="main_menu">
        <li><a href="#">都道府県から探す</a>
            <ul>
                <li><a href="">大阪府</a>
                    <ul>
                        <li><%= link_to "海遊館", searchresult_places_path(key: 1) %></li>
                        <li><%= link_to "USJ", searchresult_places_path(key: 2) %></li>
                        <li><%= link_to "難波city", searchresult_places_path(key: 3) %></li>
                        <li><%= link_to "大阪城", searchresult_places_path(key: 4) %></li>
                        <li><%= link_to "エキスポシティ", searchresult_places_path(key: 5) %></li>
                    </ul>
                </li>
                <li><a href="">京都府</a>
                    <ul>
                        <li><%= link_to "京都水族館", searchresult_places_path(key: 6) %></li>
                        <li><%= link_to "京都タワー", searchresult_places_path(key: 7) %></li>
                        <li><%= link_to "嵐山", searchresult_places_path(key: 8) %></li>
                    </ul>
                </li>
                <li><a href="">兵庫県</a>
                    <ul>
                        <li><%= link_to "城崎マリンワールド", searchresult_places_path(key: 9) %></li>
                        <li><%= link_to "メリケンパーク・ハーバーランド", searchresult_places_path(key: 10) %></li>
                        <li><%= link_to "淡路島　淡路ファームパークイングランドの丘", searchresult_places_path(key: 11) %></li>
                    </ul>
                </li>
                <li><a href="">奈良県</a>
                    <ul>
                        <li><%= link_to "奈良公園", searchresult_places_path(key: 12) %></li>
                        <li><%= link_to "ならまち", searchresult_places_path(key: 13) %></li>
                        <li><%= link_to "法隆寺", searchresult_places_path(key: 14) %></li>
                    </ul>
                </li>
                <li><a href="">和歌山県</a>
                    <ul>
                        <li><%= link_to "アドベンチャーワールド", searchresult_places_path(key: 15) %></li>
                        <li><%= link_to "とれとれ市場　南紀白浜", searchresult_places_path(key: 16) %></li>
                        <li><%= link_to "円月島", searchresult_places_path(key: 17) %></li>
                    </ul>
                </li>
                <li><a href="">滋賀県</a>
                    <ul>
                        <li><%= link_to "彦根城", searchresult_places_path(key: 18) %></li>
                        <li><%= link_to "なぎさ公園", searchresult_places_path(key: 19) %></li>
                        <li><%= link_to "びわ湖バレイ", searchresult_places_path(key: 20) %></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><a href="#">種類から探す</a>
            <ul>
                <li><a href="">テーマパーク</a>
                    <ul>
                    <li><%= link_to "USJ", searchresult_places_path(key: 2) %></li>
                    <li><%= link_to "城崎マリンワールド", searchresult_places_path(key: 9) %></li>
                    <li><%= link_to "アドベンチャーワールド", searchresult_places_path(key: 15) %></li>

                    </ul>
                </li>
                <li><a href="">動物園・水族館</a>
                    <ul>
                    <li><%= link_to "海遊館", searchresult_places_path(key: 1) %></li>
                    <li><%= link_to "京都水族館", searchresult_places_path(key: 6) %></li>
                    <li><%= link_to "アドベンチャーワールド", searchresult_places_path(key: 15) %></li>
                </li>
                    </ul>                        
                </li>
                <li><a href="">公園</a>
                    <ul>
                    <li><%= link_to "大阪城公園", searchresult_places_path(key: 4) %></li>
                    <li><%= link_to "奈良公園", searchresult_places_path(key: 12) %></li>
                    <li><%= link_to "なぎさ公園", searchresult_places_path(key: 19) %></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</nav>
</div>
</form>

app/views/places/index.html.erb
<%= render partial: "searchfunction" %><br>
<%= render partial: "place"%>

app/views/places/searchresult.html.erb
<div class="resultcontents">
  <div class="resultcontent">
    <h3 class="resultcontent__title">メインの行き先↓</h3>
    <div class="resultcontent__top">
      <div class="resultcontent__top--image"><%= image_tag "#{@place.image}", :size =>'300x150' %></div>
    </div>
    <div class="resultcontent__bottom">
      <div class="resultcontent__bottom__name">
        <%= @place.name %>
      </div>
      <div class="resultcontent__bottom__address">
        <%= @place.address %>
      </div>
      <div class="resultcontent__bottom__description">
          <%= @place.description %>
      </div>
      <div class="resultcontent__bottom__link">
        <%= link_to "#{@place.link}", "#{@place.link}" %>
      </div>
    </div>
  </div>
  <div class="if-form">
    <%= render partial: "form" %>
  </div>
</div>

<%= render partial: "place"%>

app/views/places/searchword.html.erb
<%= render partial: "place"%>