config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'places#index'
  namespace :places do
    resources :searches, only: [:index, :new, :create, :show]
  end
  resources :places, only: [:index, :show, :new] do
  collection do
    get 'searchword'
  end
  collection do
    get 'searchresult'
  end
end
  resources :posts
  resources :users, only: :show
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>decideYourPlan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
  <div class="container">
      <header class="header">
        <div class = "header__title">
          <div class="header__title__sub">休日のデートプランはお決まりですか？</div>
          <a href="/" class="header__title__container">
            <img src="/icon_145450_256.png" alt="home page icon" class="header__title__container__icon">
            <div class="header__title__container__text">Decide Your Plan "in 関西"</div>
          </a>
        </div>
        <div class="header__right">
          <% if user_signed_in? %>
            <%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>
            <%= link_to "投稿プラン一覧", places_searches_path, class: "header__right--btn" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
          <% else %>
            <%= link_to "投稿プラン一覧", places_searches_path, class: "header__right--btn" %>
            <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
            <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
          <% end %>
        </div>
      </header>
      <div class="main">
      <%= yield %>
      </div>
      <div class="footer">
          <img src="/icon_145450_256.png" alt="home page icon" class="header__title__container__icon">
          Copyright© 2020 DecideYourPlan Inc. 2020 Daisuke Ishikawa<br>
          サイト内の文章の著作物は本サイトに属します。文章の複製及び無断転載を禁じます。
          <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
            <img src="https://api.gnavi.co.jp/api/img/credit/api_90_35.gif" width="90" height="35" border="0" alt="グルメ情報検索サイト　ぐるなび">
          </a>
        </div>
    </div>
  </body>
</html>